name: Android CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Download Keystore
        run: |
          curl -L -o my-release-key.keystore "YOUR-KEYSTORE-URL" //Keystore file path
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Upload APK (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk
